services:
  - type: web
    name: campaign-management
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: campaign-db
          property: connectionString
    autoDeploy: false

databases:
  - name: campaign-db
    databaseName: campaign_management
    user: campaign_user
    plan: free